<?xml version="1.0" encoding="utf-8"?>
<Profile>
  <Name>76561198015076176</Name>
  <ID>76561198015076176</ID>
  <Mood>0.25</Mood>
  <SteamID>76561198015076176</SteamID>
  <LastKnownName>Jonno</LastKnownName>
  <Stats>
    <currentTitle></currentTitle>
    <kills>863</kills>
    <suicides>113</suicides>
    <timesKilled>1145</timesKilled>
    <matchesWon>645</matchesWon>
    <trophiesSinceLastWinCounter>3</trophiesSinceLastWinCounter>
    <trophiesSinceLastWin>4</trophiesSinceLastWin>
    <timesSpawned>2328</timesSpawned>
    <trophiesWon>30</trophiesWon>
    <gamesPlayed>70</gamesPlayed>
    <fallDeaths>203</fallDeaths>
    <timesSwore>29</timesSwore>
    <bulletsFired>12491</bulletsFired>
    <bulletsThatHit>2014</bulletsThatHit>
    <coolness>1330</coolness>
    <unarmedDucksShot>189</unarmedDucksShot>
    <killsFromTheGrave>62</killsFromTheGrave>
    <timesNetted>181</timesNetted>
    <timeInNet>560.224</timeInNet>
    <loyalFans>394</loyalFans>
    <unloyalFans>0</unloyalFans>
    <timeUnderMindControl>8.550041</timeUnderMindControl>
    <timesMindControlled>17</timesMindControlled>
    <timeOnFire>343.4436</timeOnFire>
    <timesLitOnFire>136</timesLitOnFire>
    <airTime>16712.5488</airTime>
    <timesJumped>18741</timesJumped>
    <disarms>487</disarms>
    <timesDisarmed>769</timesDisarmed>
    <quacks>4424</quacks>
    <timeWithMouthOpen>1681.4502</timeWithMouthOpen>
    <timeSpentOnMines>16.4332542</timeSpentOnMines>
    <minesSteppedOn>41</minesSteppedOn>
    <timeSpentReloadingOldTimeyWeapons>185.4655</timeSpentReloadingOldTimeyWeapons>
    <presentsOpened>161</presentsOpened>
    <respectGivenToDead>0</respectGivenToDead>
    <funeralsPerformed>1</funeralsPerformed>
    <funeralsRecieved>2</funeralsRecieved>
    <timePreaching>504.999847</timePreaching>
    <conversions>4</conversions>
    <_nodeName>Stats</_nodeName>
  </Stats>
  <Unlocks>|BASEMENTKEY|MOOGRAV|HELMY|EXPLODEYCRATES|INFAMMO|GUNEXPL|HATTY2|HATTY1|WINPRES|SHOESTAR|QWOPPY|JETTY|CORPSEBLOW|ULTIMATE</Unlocks>
  <Tickets>0</Tickets>
  <Mappings />
</Profile>