<?xml version="1.0" encoding="utf-8"?>
<Profile>
  <Name>fanjit</Name>
  <ID>b7a67cbf-bf83-4e20-82ec-0a8a29890425</ID>
  <Mood>0</Mood>
  <SteamID>0</SteamID>
  <Stats>
    <currentTitle></currentTitle>
    <kills>372</kills>
    <suicides>35</suicides>
    <timesKilled>527</timesKilled>
    <matchesWon>314</matchesWon>
    <trophiesSinceLastWinCounter>1</trophiesSinceLastWinCounter>
    <trophiesSinceLastWin>1</trophiesSinceLastWin>
    <timesSpawned>844</timesSpawned>
    <trophiesWon>20</trophiesWon>
    <gamesPlayed>31</gamesPlayed>
    <fallDeaths>50</fallDeaths>
    <timesSwore>9</timesSwore>
    <bulletsFired>3558</bulletsFired>
    <bulletsThatHit>246</bulletsThatHit>
    <coolness>469</coolness>
    <unarmedDucksShot>87</unarmedDucksShot>
    <killsFromTheGrave>21</killsFromTheGrave>
    <timesNetted>54</timesNetted>
    <timeInNet>202.7946</timeInNet>
    <loyalFans>42</loyalFans>
    <unloyalFans>16</unloyalFans>
    <timeUnderMindControl>2.14999866</timeUnderMindControl>
    <timesMindControlled>6</timesMindControlled>
    <timeOnFire>142.259384</timeOnFire>
    <timesLitOnFire>48</timesLitOnFire>
    <airTime>7582.39551</airTime>
    <timesJumped>9280</timesJumped>
    <disarms>327</disarms>
    <timesDisarmed>422</timesDisarmed>
    <quacks>5835</quacks>
    <timeWithMouthOpen>729.9159</timeWithMouthOpen>
    <timeSpentOnMines>5.21667957</timeSpentOnMines>
    <minesSteppedOn>31</minesSteppedOn>
    <timeSpentReloadingOldTimeyWeapons>96.23941</timeSpentReloadingOldTimeyWeapons>
    <presentsOpened>90</presentsOpened>
    <respectGivenToDead>0</respectGivenToDead>
    <funeralsPerformed>2</funeralsPerformed>
    <funeralsRecieved>2</funeralsRecieved>
    <timePreaching>377.6667</timePreaching>
    <conversions>9</conversions>
    <_timesKilledBy>
      <pair>
        <key></key>
        <val>10</val>
      </pair>
      <pair>
        <key>{murreh{</key>
        <val>7</val>
      </pair>
      <pair>
        <key>Jonno</key>
        <val>9</val>
      </pair>
      <pair>
        <key>fanjit</key>
        <val>3</val>
      </pair>
    </_timesKilledBy>
    <_nodeName>Stats</_nodeName>
  </Stats>
  <Unlocks></Unlocks>
  <Tickets>0</Tickets>
  <Mappings />
</Profile>