<?xml version="1.0" encoding="utf-8"?>
<Profile>
  <Name>Player2</Name>
  <ID>PLAYER2</ID>
  <Mood>0.5</Mood>
  <SteamID>0</SteamID>
  <Stats>
    <currentTitle></currentTitle>
    <kills>58</kills>
    <suicides>13</suicides>
    <timesKilled>88</timesKilled>
    <matchesWon>54</matchesWon>
    <trophiesSinceLastWinCounter>1</trophiesSinceLastWinCounter>
    <trophiesSinceLastWin>1</trophiesSinceLastWin>
    <timesSpawned>145</timesSpawned>
    <trophiesWon>3</trophiesWon>
    <gamesPlayed>5</gamesPlayed>
    <fallDeaths>6</fallDeaths>
    <timesSwore>4</timesSwore>
    <bulletsFired>772</bulletsFired>
    <bulletsThatHit>33</bulletsThatHit>
    <coolness>43</coolness>
    <unarmedDucksShot>18</unarmedDucksShot>
    <killsFromTheGrave>7</killsFromTheGrave>
    <timesNetted>12</timesNetted>
    <timeInNet>38.4162521</timeInNet>
    <loyalFans>0</loyalFans>
    <unloyalFans>0</unloyalFans>
    <timeUnderMindControl>0</timeUnderMindControl>
    <timesMindControlled>0</timesMindControlled>
    <timeOnFire>23.4498138</timeOnFire>
    <timesLitOnFire>7</timesLitOnFire>
    <airTime>1412.969</airTime>
    <timesJumped>1661</timesJumped>
    <disarms>38</disarms>
    <timesDisarmed>60</timesDisarmed>
    <quacks>739</quacks>
    <timeWithMouthOpen>88.571106</timeWithMouthOpen>
    <timeSpentOnMines>1.083333</timeSpentOnMines>
    <minesSteppedOn>5</minesSteppedOn>
    <timeSpentReloadingOldTimeyWeapons>39.7495651</timeSpentReloadingOldTimeyWeapons>
    <presentsOpened>7</presentsOpened>
    <respectGivenToDead>1</respectGivenToDead>
    <funeralsPerformed>0</funeralsPerformed>
    <funeralsRecieved>0</funeralsRecieved>
    <timePreaching>33</timePreaching>
    <conversions>0</conversions>
    <_nodeName>Stats</_nodeName>
  </Stats>
  <Unlocks></Unlocks>
  <Tickets>0</Tickets>
  <Mappings />
</Profile>