<?xml version="1.0" encoding="utf-8"?>
<Profile>
  <Name>Player1</Name>
  <ID>PLAYER1</ID>
  <Mood>0.5</Mood>
  <SteamID>0</SteamID>
  <Stats>
    <currentTitle></currentTitle>
    <kills>33</kills>
    <suicides>4</suicides>
    <timesKilled>58</timesKilled>
    <matchesWon>31</matchesWon>
    <trophiesSinceLastWinCounter>3</trophiesSinceLastWinCounter>
    <trophiesSinceLastWin>1</trophiesSinceLastWin>
    <timesSpawned>99</timesSpawned>
    <trophiesWon>1</trophiesWon>
    <gamesPlayed>4</gamesPlayed>
    <fallDeaths>10</fallDeaths>
    <timesSwore>1</timesSwore>
    <bulletsFired>462</bulletsFired>
    <bulletsThatHit>83</bulletsThatHit>
    <coolness>10</coolness>
    <unarmedDucksShot>10</unarmedDucksShot>
    <killsFromTheGrave>1</killsFromTheGrave>
    <timesNetted>6</timesNetted>
    <timeInNet>23.04982</timeInNet>
    <loyalFans>1</loyalFans>
    <unloyalFans>3</unloyalFans>
    <timeUnderMindControl>0.0166666675</timeUnderMindControl>
    <timesMindControlled>1</timesMindControlled>
    <timeOnFire>16.7499161</timeOnFire>
    <timesLitOnFire>5</timesLitOnFire>
    <airTime>735.5812</airTime>
    <timesJumped>798</timesJumped>
    <disarms>16</disarms>
    <timesDisarmed>20</timesDisarmed>
    <quacks>168</quacks>
    <timeWithMouthOpen>22.566494</timeWithMouthOpen>
    <timeSpentOnMines>0.2</timeSpentOnMines>
    <minesSteppedOn>2</minesSteppedOn>
    <timeSpentReloadingOldTimeyWeapons>4.116665</timeSpentReloadingOldTimeyWeapons>
    <presentsOpened>2</presentsOpened>
    <respectGivenToDead>0</respectGivenToDead>
    <funeralsPerformed>0</funeralsPerformed>
    <funeralsRecieved>0</funeralsRecieved>
    <timePreaching>0</timePreaching>
    <conversions>0</conversions>
    <_nodeName>Stats</_nodeName>
  </Stats>
  <Unlocks></Unlocks>
  <Tickets>30</Tickets>
  <Mappings />
</Profile>