<?xml version="1.0" encoding="utf-8"?>
<Profile>
  <Name>Player3</Name>
  <ID>PLAYER3</ID>
  <Mood>0.5</Mood>
  <SteamID>0</SteamID>
  <Stats>
    <currentTitle></currentTitle>
    <kills>23</kills>
    <suicides>13</suicides>
    <timesKilled>113</timesKilled>
    <matchesWon>22</matchesWon>
    <trophiesSinceLastWinCounter>5</trophiesSinceLastWinCounter>
    <trophiesSinceLastWin>0</trophiesSinceLastWin>
    <timesSpawned>139</timesSpawned>
    <trophiesWon>0</trophiesWon>
    <gamesPlayed>5</gamesPlayed>
    <fallDeaths>15</fallDeaths>
    <timesSwore>7</timesSwore>
    <bulletsFired>400</bulletsFired>
    <bulletsThatHit>16</bulletsThatHit>
    <coolness>-64</coolness>
    <unarmedDucksShot>9</unarmedDucksShot>
    <killsFromTheGrave>2</killsFromTheGrave>
    <timesNetted>13</timesNetted>
    <timeInNet>41.5995369</timeInNet>
    <loyalFans>0</loyalFans>
    <unloyalFans>0</unloyalFans>
    <timeUnderMindControl>0</timeUnderMindControl>
    <timesMindControlled>0</timesMindControlled>
    <timeOnFire>17.999897</timeOnFire>
    <timesLitOnFire>6</timesLitOnFire>
    <airTime>1037.47327</airTime>
    <timesJumped>1468</timesJumped>
    <disarms>60</disarms>
    <timesDisarmed>102</timesDisarmed>
    <quacks>329</quacks>
    <timeWithMouthOpen>56.81597</timeWithMouthOpen>
    <timeSpentOnMines>0.5000002</timeSpentOnMines>
    <minesSteppedOn>3</minesSteppedOn>
    <timeSpentReloadingOldTimeyWeapons>9.466694</timeSpentReloadingOldTimeyWeapons>
    <presentsOpened>3</presentsOpened>
    <respectGivenToDead>0</respectGivenToDead>
    <funeralsPerformed>0</funeralsPerformed>
    <funeralsRecieved>0</funeralsRecieved>
    <timePreaching>0</timePreaching>
    <conversions>0</conversions>
    <_nodeName>Stats</_nodeName>
  </Stats>
  <Unlocks></Unlocks>
  <Tickets>0</Tickets>
  <Mappings />
</Profile>