<?xml version="1.0" encoding="utf-8"?>
<Profile>
  <Name>s</Name>
  <ID>5097c358-c732-4e02-93a6-fa76aca17209</ID>
  <Mood>0.5</Mood>
  <SteamID>0</SteamID>
  <Stats>
    <currentTitle></currentTitle>
    <kills>20</kills>
    <suicides>2</suicides>
    <timesKilled>33</timesKilled>
    <matchesWon>7</matchesWon>
    <trophiesSinceLastWinCounter>1</trophiesSinceLastWinCounter>
    <trophiesSinceLastWin>0</trophiesSinceLastWin>
    <timesSpawned>40</timesSpawned>
    <trophiesWon>0</trophiesWon>
    <gamesPlayed>1</gamesPlayed>
    <fallDeaths>0</fallDeaths>
    <timesSwore>0</timesSwore>
    <bulletsFired>117</bulletsFired>
    <bulletsThatHit>14</bulletsThatHit>
    <coolness>9</coolness>
    <unarmedDucksShot>4</unarmedDucksShot>
    <killsFromTheGrave>0</killsFromTheGrave>
    <timesNetted>4</timesNetted>
    <timeInNet>7.550044</timeInNet>
    <loyalFans>0</loyalFans>
    <unloyalFans>0</unloyalFans>
    <timeUnderMindControl>0</timeUnderMindControl>
    <timesMindControlled>0</timesMindControlled>
    <timeOnFire>4.233333</timeOnFire>
    <timesLitOnFire>2</timesLitOnFire>
    <airTime>277.659668</airTime>
    <timesJumped>405</timesJumped>
    <disarms>4</disarms>
    <timesDisarmed>11</timesDisarmed>
    <quacks>8</quacks>
    <timeWithMouthOpen>2.86666465</timeWithMouthOpen>
    <timeSpentOnMines>0.216666669</timeSpentOnMines>
    <minesSteppedOn>3</minesSteppedOn>
    <timeSpentReloadingOldTimeyWeapons>4.116665</timeSpentReloadingOldTimeyWeapons>
    <presentsOpened>0</presentsOpened>
    <respectGivenToDead>0</respectGivenToDead>
    <funeralsPerformed>0</funeralsPerformed>
    <funeralsRecieved>0</funeralsRecieved>
    <timePreaching>0</timePreaching>
    <conversions>0</conversions>
    <_timesKilledBy>
      <pair>
        <key>fanjit</key>
        <val>6</val>
      </pair>
      <pair>
        <key>s</key>
        <val>2</val>
      </pair>
      <pair>
        <key>Jonno</key>
        <val>6</val>
      </pair>
      <pair>
        <key>{murreh{</key>
        <val>14</val>
      </pair>
      <pair>
        <key></key>
        <val>5</val>
      </pair>
    </_timesKilledBy>
    <_nodeName>Stats</_nodeName>
  </Stats>
  <Unlocks></Unlocks>
  <Tickets>0</Tickets>
  <Mappings />
</Profile>