<?xml version="1.0" encoding="utf-8"?>
<Profile>
  <Name>{murreh{</Name>
  <ID>1dddd319-4479-49f7-8e25-cd1b545c64aa</ID>
  <Mood>0</Mood>
  <SteamID>0</SteamID>
  <Stats>
    <currentTitle></currentTitle>
    <kills>654</kills>
    <suicides>148</suicides>
    <timesKilled>1132</timesKilled>
    <matchesWon>540</matchesWon>
    <trophiesSinceLastWinCounter>5</trophiesSinceLastWinCounter>
    <trophiesSinceLastWin>9</trophiesSinceLastWin>
    <timesSpawned>1636</timesSpawned>
    <trophiesWon>17</trophiesWon>
    <gamesPlayed>65</gamesPlayed>
    <fallDeaths>123</fallDeaths>
    <timesSwore>20</timesSwore>
    <bulletsFired>5770</bulletsFired>
    <bulletsThatHit>352</bulletsThatHit>
    <coolness>783</coolness>
    <unarmedDucksShot>165</unarmedDucksShot>
    <killsFromTheGrave>69</killsFromTheGrave>
    <timesNetted>126</timesNetted>
    <timeInNet>374.219421</timeInNet>
    <loyalFans>31</loyalFans>
    <unloyalFans>9</unloyalFans>
    <timeUnderMindControl>7.233373</timeUnderMindControl>
    <timesMindControlled>14</timesMindControlled>
    <timeOnFire>342.9104</timeOnFire>
    <timesLitOnFire>133</timesLitOnFire>
    <airTime>14389.7</airTime>
    <timesJumped>18864</timesJumped>
    <disarms>609</disarms>
    <timesDisarmed>671</timesDisarmed>
    <quacks>6966</quacks>
    <timeWithMouthOpen>1092.84521</timeWithMouthOpen>
    <timeSpentOnMines>18.2498932</timeSpentOnMines>
    <minesSteppedOn>39</minesSteppedOn>
    <timeSpentReloadingOldTimeyWeapons>128.796</timeSpentReloadingOldTimeyWeapons>
    <presentsOpened>155</presentsOpened>
    <respectGivenToDead>0</respectGivenToDead>
    <funeralsPerformed>2</funeralsPerformed>
    <funeralsRecieved>1</funeralsRecieved>
    <timePreaching>687.1666</timePreaching>
    <conversions>7</conversions>
    <_timesKilledBy>
      <pair>
        <key></key>
        <val>13</val>
      </pair>
      <pair>
        <key>{murreh{</key>
        <val>7</val>
      </pair>
      <pair>
        <key>Jonno</key>
        <val>17</val>
      </pair>
      <pair>
        <key>fanjit</key>
        <val>5</val>
      </pair>
    </_timesKilledBy>
    <_nodeName>Stats</_nodeName>
  </Stats>
  <Unlocks></Unlocks>
  <Tickets>0</Tickets>
  <Mappings />
</Profile>